version: '3.9'
services:
  php-env:
    build:
      context: .  
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./logs:/var/www/html/logs
    ports:
      - 80:80

